# Generated by Django 6.1.1 on 2026-09-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tatuador_nombre', models.CharField(blank=True, max_length=100)),
                ('estilo', models.CharField(choices=[('tradicional', 'Tradicional'), ('realismo', 'Realismo'), ('blackwork', 'Blackwork'), ('acuarela', 'Acuarela'), ('minimalista', 'Minimalista')], default='tradicional', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tiempo_estimado_horas', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
