# Generated by Django 6.1.1 on 2026-09-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tatuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(choices=[('tradicional', 'Tradicional'), ('realismo', 'Realismo'), ('blackwork', 'Blackwork'), ('acuarela', 'Acuarela'), ('minimalista', 'Minimalista')], default='tradicional', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('anios_experiencia', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
