# Generated by Django 6.1.1 on 2026-09-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='cliente_nombre',
            new_name='nombre_cliente',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='tatuador_nombre',
            new_name='nombre_tatuador',
        ),
    ]
